export const categories = [
  "Landscaping / Lawn Care",
  "Plumbing",
  "Roofing",
  "Cleaning Services",
  "Auto Repair / Mechanics",
  "HVAC / Electrical",
  "General Contractor",
  "Restaurant / Food",
  "Other",
];

export const websiteStatuses = ["None", "Outdated", "Basic", "Good"];
export const socialStatuses = ["None", "Low", "Moderate", "Active"];
export const leadStatuses = [
  "Not Contacted",
  "Contacted",
  "Interested",
  "Not Interested",
  "Closed",
];
export const activityTypes = [
  "Called",
  "Emailed",
  "Texted",
  "Visited",
  "Voicemail",
  "Follow-up",
  "Other",
];
export const tags = [
  "Hot Lead",
  "Needs Website",
  "Needs Social",
  "Follow Up",
  "Quoted",
  "Won",
  "Lost",
  "VIP",
  "Referral",
];

export const tagColors: Record<string, string> = {
  "Hot Lead": "bg-red-500/20 text-red-400 border-red-500/25",
  "Needs Website": "bg-orange-500/20 text-orange-400 border-orange-500/25",
  "Needs Social": "bg-amber-500/20 text-amber-400 border-amber-500/25",
  "Follow Up": "bg-blue-500/20 text-blue-400 border-blue-500/25",
  Quoted: "bg-violet-500/20 text-violet-400 border-violet-500/25",
  Won: "bg-emerald-500/20 text-emerald-400 border-emerald-500/25",
  Lost: "bg-gray-500/20 text-gray-400 border-gray-500/25",
  VIP: "bg-amber-400/20 text-amber-300 border-amber-400/25",
  Referral: "bg-cyan-500/20 text-cyan-400 border-cyan-500/25",
};

export const activityIcons: Record<string, string> = {
  Called: "📞",
  Emailed: "📧",
  Texted: "💬",
  Visited: "🚗",
  Voicemail: "📱",
  "Follow-up": "🔄",
  Other: "📝",
};

export const websiteStatusColors: Record<string, string> = {
  None: "bg-red-500/10 text-red-400 border-red-500/20",
  Outdated: "bg-yellow-500/10 text-yellow-400 border-yellow-500/20",
  Basic: "bg-sky-500/10 text-sky-400 border-sky-500/20",
  Good: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
};

export const socialStatusColors: Record<string, string> = {
  None: "bg-red-500/10 text-red-400 border-red-500/20",
  Low: "bg-orange-500/10 text-orange-400 border-orange-500/20",
  Moderate: "bg-yellow-500/10 text-yellow-400 border-yellow-500/20",
  Active: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
};

export const leadStatusColors: Record<string, string> = {
  "Not Contacted": "bg-zinc-500/10 text-zinc-400 border-zinc-500/20",
  Contacted: "bg-blue-500/10 text-blue-400 border-blue-500/20",
  Interested: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
  "Not Interested": "bg-red-500/10 text-red-400 border-red-500/20",
  Closed: "bg-violet-500/10 text-violet-400 border-violet-500/20",
};

export const categoryIcons: Record<string, string> = {
  "Landscaping / Lawn Care": "🌿",
  Plumbing: "🔧",
  Roofing: "🏠",
  "Cleaning Services": "🧹",
  "Auto Repair / Mechanics": "🚗",
  "HVAC / Electrical": "⚡",
  "General Contractor": "🏗️",
  "Restaurant / Food": "🍽️",
  Other: "📁",
};

export const leadStatusChartColors: Record<string, string> = {
  "Not Contacted": "#71717a",
  Contacted: "#3b82f6",
  Interested: "#10b981",
  "Not Interested": "#ef4444",
  Closed: "#8b5cf6",
};

export const templates: Record<string, any> = {
  "Landscaping / Lawn Care": {
    emailSubject: "Quick idea to get {{businessName}} more landscaping clients",
    emailBody: `Hi {{ownerName}},

I came across {{businessName}} and was really impressed by your work and reputation in the {{category}} space. Your reviews speak for themselves.

I noticed you don't currently have a website, and I think that's a huge missed opportunity. Most homeowners search online before hiring a landscaper, and right now potential clients in your area can't find you on Google.

I specialize in building affordable, professional websites for landscaping businesses. I'm talking about a clean site that showcases your work with photos, lists your services, and makes it easy for customers to call or request a quote -- usually up and running within a week.

Would you be open to a quick 10-minute call this week to see if it's a fit? No pressure at all.

Looking forward to hearing from you,
[Your Name]`,
    callScript:
      "Hi, is this {{ownerName}}? Hey, my name is [Your Name] and I help local landscaping businesses get more clients through websites and online marketing. I came across {{businessName}} and noticed you have great reviews but no website yet. Most homeowners search Google before hiring a landscaper, and I'd love to help you show up when they do. I build clean, professional sites specifically for landscaping companies -- usually ready in about a week. Would you have a few minutes this week to chat about it?",
    textMessage:
      "Hi {{ownerName}}, this is [Your Name]. I came across {{businessName}} and was impressed by your work. I noticed you don't have a website yet -- I help landscaping businesses get found online with affordable websites. Would you be open to a quick chat? No pressure at all.",
  },
  Plumbing: {
    emailSubject: "Helping {{businessName}} get more calls from local customers",
    emailBody: `Hi {{ownerName}},

I was researching local plumbing companies and came across {{businessName}}. It's clear you've built a solid reputation in the community.

I noticed you don't have a website (or your current site could use an update), and I wanted to reach out because I help plumbing businesses like yours get more calls from local homeowners through professional websites and Google visibility.

Think about it -- when someone has a burst pipe or a clogged drain, the first thing they do is search "plumber near me" on their phone. Without a website, those emergency calls are going to your competitors instead.

I build fast-loading, mobile-friendly websites for plumbers that are designed to convert visitors into phone calls. Most of my clients see an increase in calls within the first month.

Could we set up a quick 10-minute call to talk about what this might look like for {{businessName}}?

Best,
[Your Name]`,
    callScript:
      "Hi, is this {{ownerName}}? My name is [Your Name] and I work with local plumbing companies to help them get more calls through their online presence. I came across {{businessName}} and noticed you either don't have a website or it could use a refresh. When people have plumbing emergencies, they search on their phone first -- and if you're not showing up, those calls go to someone else. I build affordable, mobile-friendly sites specifically for plumbers. Could we chat for a few minutes this week about getting you set up?",
    textMessage: `Hi {{ownerName}}, this is [Your Name]. I work with local plumbers to help them get more calls online. I noticed {{businessName}} doesn't have a website yet -- when customers search "plumber near me," you're missing out on those calls. I'd love to help change that. Open to a quick chat?`,
  },
  Roofing: {
    emailSubject: "{{businessName}} -- an idea to land more roofing jobs",
    emailBody: `Hi {{ownerName}},

I came across {{businessName}} while looking into top roofing companies in the area, and your track record is impressive.

I noticed you don't have a website right now (or your current one could use a refresh). For roofing companies especially, this is a big deal -- roofing is one of the most-searched home services online, and homeowners almost always check a company's website before requesting a quote.

I specialize in building professional websites for roofing companies that showcase your completed projects, highlight your licensing and insurance, and make it dead simple for homeowners to request an estimate.

The best part? I can usually have everything up and running within a week, and it's way more affordable than you might think.

Would you be open to a quick conversation this week to see if this makes sense for {{businessName}}?

Thanks,
[Your Name]`,
    callScript:
      "Hi, is this {{ownerName}}? Hey, this is [Your Name]. I help local roofing companies get more jobs through professional websites and online marketing. I found {{businessName}} and noticed you don't currently have a website -- or your current site could use an update. Roofing is one of the most-searched home services, and homeowners always check a company's site before requesting a quote. I build sites that showcase your projects and make it easy for people to request estimates. Would you have 10 minutes this week to talk about it?",
    textMessage:
      "Hi {{ownerName}}, this is [Your Name]. I found {{businessName}} and was impressed by your work. I noticed you don't have a website -- homeowners almost always check online before hiring a roofer. I build affordable sites for roofing companies that help you land more jobs. Interested in a quick chat?",
  },
  "Cleaning Services": {
    emailSubject: "Idea to help {{businessName}} book more cleaning clients",
    emailBody: `Hi {{ownerName}},

I came across {{businessName}} and could tell you take a lot of pride in your cleaning business. Your loyal customers clearly appreciate your work.

I wanted to reach out because I noticed you don't have a website, and I think you're leaving a lot of new business on the table. More and more people search online to find cleaning services -- they want to see what you offer, read reviews, and have an easy way to book or call.

I help cleaning businesses like yours get set up with a professional, simple website that builds trust and makes it easy for new clients to reach you. It's affordable, and I can have it ready in under a week.

Would you be open to a short phone call to see if this could work for {{businessName}}?

Warm regards,
[Your Name]`,
    callScript:
      "Hi, is this {{ownerName}}? My name is [Your Name] and I help local cleaning businesses get more clients online. I found {{businessName}} and saw your great reputation, but I noticed you don't have a website yet. More and more people search online to find cleaning services, and without a site, they can't find you. I build simple, professional websites for cleaning companies that make it easy for new clients to book with you. Would you have a few minutes to chat about it this week?",
    textMessage:
      "Hi {{ownerName}}, this is [Your Name]. I found {{businessName}} and could tell you do great work. I noticed you don't have a website yet -- I help cleaning businesses get found online with professional sites that bring in new clients. Would you be open to a quick call?",
  },
  "Auto Repair / Mechanics": {
    emailSubject: "Getting {{businessName}} in front of more local drivers",
    emailBody: `Hi {{ownerName}},

I came across {{businessName}} while researching local auto repair shops, and it's clear you've built a strong reputation with your customers.

I noticed you don't currently have a website (or your current site could use a facelift). In the auto repair world, this matters a lot -- when someone's car breaks down or they need a trusted mechanic, the first thing they do is search on their phone. If you don't show up, they end up at a chain shop instead.

I build professional, mobile-friendly websites specifically for auto repair shops. I'm talking about a site that lists your services, shows your shop hours and location, highlights your experience, and makes it easy for people to call you directly.

It's more affordable than you'd expect, and I can have it ready quickly.

Would you be open to a brief call this week to discuss?

Thanks,
[Your Name]`,
    callScript:
      "Hi, is this {{ownerName}}? Hey, this is [Your Name]. I help local auto repair shops get more customers through professional websites. I came across {{businessName}} and could see you have a great reputation, but I noticed you're missing a website -- or yours needs an update. When people's cars break down, they search on their phone first, and if you're not online, they end up at a chain shop. I build affordable sites for mechanics that are ready in about a week. Do you have a few minutes to chat about it?",
    textMessage:
      "Hi {{ownerName}}, this is [Your Name]. I found {{businessName}} and was impressed by your reputation. I noticed you don't have a website -- when drivers need a mechanic, they search online first. I build affordable sites for auto repair shops. Open to a quick call to talk about it?",
  },
  "HVAC / Electrical": {
    emailSubject: "Helping {{businessName}} get more service calls this season",
    emailBody: `Hi {{ownerName}},

I came across {{businessName}} and was impressed by your experience and reputation in the HVAC/electrical space.

I noticed you don't have a website right now (or your current one could use an update). For HVAC and electrical businesses, this is especially critical -- when someone's AC goes out in the summer or they have an electrical issue, they grab their phone and search for help immediately. Without a website, you're invisible to those customers.

I specialize in building professional websites for HVAC and electrical companies. A good site showcases your services, licensing, and experience -- and most importantly, it makes it incredibly easy for someone to call you right from their phone.

It's affordable and I can get it done fast. Would you be open to a 10-minute call this week to explore this?

Best,
[Your Name]`,
    callScript:
      "Hi, is this {{ownerName}}? My name is [Your Name] and I help HVAC and electrical businesses get more service calls through professional websites and online marketing. I found {{businessName}} and noticed you don't have a website yet -- or it could use a refresh. When someone's AC dies or they have an electrical emergency, they search on their phone first. Without a website, those calls go to your competitors. I build affordable, professional sites for HVAC companies that are designed to convert. Do you have a few minutes to talk about it?",
    textMessage:
      "Hi {{ownerName}}, this is [Your Name]. I found {{businessName}} and was impressed by your work. I noticed you don't have a website -- when people need HVAC or electrical help, they search online first. I build affordable sites that help you get those calls. Interested in a quick chat?",
  },
  "General Contractor": {
    emailSubject: "Quick way to get {{businessName}} more jobs",
    emailBody: `Hi {{ownerName}},

I found {{businessName}} while researching local contractors, and your experience really stands out.

I noticed you don't have a website yet (or your current one could use an upgrade). As a contractor, your work speaks for itself -- but potential clients need to be able to find you and see that work before they pick up the phone.

I help general contractors and handymen get professional websites that showcase their projects, list their services, and make it simple for homeowners to request a quote. Think of it as your 24/7 business card that works while you're on the job.

It's affordable, fast to set up, and designed specifically for the contracting industry.

Would you have 10 minutes this week for a quick call? I'd love to show you what I have in mind.

Thanks,
[Your Name]`,
    callScript:
      "Hi, is this {{ownerName}}? Hey, this is [Your Name]. I help local contractors and handymen get more jobs through professional websites. I found {{businessName}} and saw your solid reputation, but noticed you don't have a website. Homeowners want to see your past work and services before they call -- a professional site does that for you 24/7. I build affordable contractor websites that are ready in about a week. Would you have a few minutes to chat this week?",
    textMessage:
      "Hi {{ownerName}}, this is [Your Name]. I found {{businessName}} and was impressed by your work. I noticed you don't have a website yet -- homeowners want to see your projects before they hire. I build affordable contractor sites that help you land more jobs. Open to a quick call?",
  },
  "Restaurant / Food": {
    emailSubject: "Idea to bring more customers into {{businessName}}",
    emailBody: `Hi {{ownerName}},

I came across {{businessName}} and could see right away that you have a loyal following -- your reviews are fantastic.

I noticed you don't have your own website, and I think there's a big opportunity here. Right now when people search for places to eat in your area, they see Yelp and Google listings -- but those platforms control your brand and take a cut. With your own website, you can showcase your menu, share your story, promote specials, and even take online orders directly.

I build clean, appetizing websites specifically for restaurants and food businesses. It's affordable, looks great on phones (where most people search), and I can have it ready in under a week.

Would you be open to a quick call to talk about what this could look like for {{businessName}}?

Best,
[Your Name]`,
    callScript:
      "Hi, is this {{ownerName}}? My name is [Your Name] and I help local restaurants get more customers through professional websites. I found {{businessName}} and your reviews are amazing -- but I noticed you don't have your own website. Right now Yelp and Google control your brand. With your own site, you can show off your menu, tell your story, promote specials, and even take orders directly. I build affordable restaurant websites that look great on phones and are ready in under a week. Would you have a few minutes to talk about it?",
    textMessage:
      "Hi {{ownerName}}, this is [Your Name]. I found {{businessName}} and your food looks amazing. I noticed you don't have your own website yet -- with one, you can showcase your menu, promote specials, and take orders directly instead of depending on Yelp. I build affordable restaurant sites fast. Interested in a quick chat?",
  },
  Other: {
    emailSubject: "Quick idea to help {{businessName}} grow online",
    emailBody: `Hi {{ownerName}},

I came across {{businessName}} and was impressed by what you've built. It's clear you have a strong reputation in your community.

I noticed you don't currently have a website (or your current site could use an update), and I wanted to reach out because I help local businesses like yours establish a professional online presence that brings in new customers.

These days, most people search online before choosing a local business. Without a website, you're invisible to those potential customers -- and your competitors who do have one are getting those calls instead.

I build affordable, professional websites for local businesses that are mobile-friendly, easy to navigate, and designed to turn visitors into customers. Most projects are done in under a week.

Would you be open to a quick 10-minute call to see if this makes sense for {{businessName}}?

Best regards,
[Your Name]`,
    callScript:
      "Hi, is this {{ownerName}}? My name is [Your Name] and I help local businesses get more customers through professional websites and digital marketing. I found {{businessName}} and was impressed by your reputation, but I noticed you don't have a website -- or it could use an update. Most people search online before choosing a local business, and without a site, those customers go somewhere else. I build affordable, mobile-friendly websites that are ready in under a week. Would you have a few minutes to talk about it?",
    textMessage:
      "Hi {{ownerName}}, this is [Your Name]. I found {{businessName}} and was impressed by your work. I noticed you don't have a website yet -- most customers search online first these days. I build affordable, professional sites for local businesses. Would you be open to a quick chat?",
  },
};

export const initialLeads = [
  {
    id: 1,
    businessName: "Grow Green Landscaping",
    category: "Landscaping / Lawn Care",
    phone: "(323) 618-9224",
    address: "Los Angeles, CA",
    ownerName: "Hugo",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "Low",
    leadStatus: "Not Contacted",
    notes:
      "Owner Hugo started since 2000. Has Nextdoor + Facebook but NO website. HIGH PRIORITY.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website"],
    activities: [],
  },
  {
    id: 2,
    businessName: "R & G Gardening Services",
    category: "Landscaping / Lawn Care",
    phone: "",
    address: "Valley Village, CA 91401",
    ownerName: "Ricardo N.",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "Low",
    leadStatus: "Not Contacted",
    notes: "Since 2008. 90 Yelp reviews. Only Yelp + Nextdoor. SFV.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website"],
    activities: [],
  },
  {
    id: 3,
    businessName: "Star Lawn Care Los Angeles",
    category: "Landscaping / Lawn Care",
    phone: "(323) 672-4996",
    address: "767 N Hill St, Los Angeles, CA 90012",
    ownerName: "",
    email: "",
    websiteUrl: "https://lawncarelosangelesca.com",
    websiteStatus: "Basic",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Basic website + Square placeholder. Serves Downtown LA area.",
    dateAdded: "2026-03-24",
    tags: ["Needs Social"],
    activities: [],
  },
  {
    id: 4,
    businessName: "L.A. Green Landscaping",
    category: "Landscaping / Lawn Care",
    phone: "(323) 901-4720",
    address: "4807 Saturn St, Los Angeles, CA 90019",
    ownerName: "Josephina Franco",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes:
      "Licensed C-27 #830393. A+ BBB. 20+ yrs. NO website. VERY HIGH PRIORITY.",
    dateAdded: "2026-03-24",
    tags: ["VIP", "Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 5,
    businessName: "Gardening Services Ramos",
    category: "Landscaping / Lawn Care",
    phone: "(323) 214-3618",
    address: "Los Angeles, CA 90016",
    ownerName: "",
    email: "",
    websiteUrl: "https://serviciodejardineriaramos.com",
    websiteStatus: "Basic",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Basic website, no social. Open 7 days.",
    dateAdded: "2026-03-24",
    tags: ["Needs Social"],
    activities: [],
  },
  {
    id: 6,
    businessName: "Gonzalez & Sons Landscaping",
    category: "Landscaping / Lawn Care",
    phone: "(323) 545-6839",
    address: "1532 S Curson Ave, Los Angeles, CA 90019",
    ownerName: "Sam",
    email: "gonzalez-n-sons@att.net",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "61 YEARS in business! Ask for Sam. NO website.",
    dateAdded: "2026-03-24",
    tags: ["VIP", "Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 7,
    businessName: "Chop Chop Landscaping",
    category: "Landscaping / Lawn Care",
    phone: "(213) 401-2441",
    address: "1201 W 5th St, Los Angeles, CA 90017",
    ownerName: "",
    email: "",
    websiteUrl: "https://www.landscapedesignerlosangeles.com",
    websiteStatus: "Good",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Polished website. No social media. SM management candidate.",
    dateAdded: "2026-03-24",
    tags: ["Needs Social"],
    activities: [],
  },
  {
    id: 8,
    businessName: "Bromen Lawn Care",
    category: "Landscaping / Lawn Care",
    phone: "(818) 310-6542",
    address: "Sylmar, CA",
    ownerName: "Jesse",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "Low",
    leadStatus: "Not Contacted",
    notes: "Family-owned. 4.5 stars Yelp. Serves SFV. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website"],
    activities: [],
  },
  {
    id: 9,
    businessName: "Eddie's Landscaping & Tree",
    category: "Landscaping / Lawn Care",
    phone: "(747) 253-8210",
    address: "Sylmar, CA 91342",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Est. 2012. 144 Yelp photos. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 10,
    businessName: "C&C Landscaping",
    category: "Landscaping / Lawn Care",
    phone: "(661) 227-6099",
    address: "Lancaster, CA 93534",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Open 24/7. NO website. Lancaster.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 11,
    businessName: "Martinez Landscaping",
    category: "Landscaping / Lawn Care",
    phone: "(661) 503-9273",
    address: "Palmdale, CA 93552",
    ownerName: "Martinez",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Open daily. Yelp only. Palmdale.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 12,
    businessName: "Hector Landscape & Construction",
    category: "Landscaping / Lawn Care",
    phone: "(661) 743-4158",
    address: "Lancaster, CA 93535",
    ownerName: "Hector",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "5.0 stars Yelp, 306 photos. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 13,
    businessName: "Gabriel Gardening",
    category: "Landscaping / Lawn Care",
    phone: "(805) 573-4881",
    address: "Lancaster, CA 93535",
    ownerName: "Gabriel",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Since 1998. 25+ years! NO website.",
    dateAdded: "2026-03-24",
    tags: ["VIP", "Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 14,
    businessName: "JPL Landscaping",
    category: "Landscaping / Lawn Care",
    phone: "",
    address: "Sylmar, CA",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "19 yrs experience. Serves LA/SCV. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 15,
    businessName: "Olivares Gardening",
    category: "Landscaping / Lawn Care",
    phone: "",
    address: "Santa Clarita / Palmdale, CA",
    ownerName: "Jose Olivares",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Since 2006. Only on GreenPal. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 16,
    businessName: "Harry L. Bailey Plumbing",
    category: "Plumbing",
    phone: "(323) 666-2255",
    address: "418 N Hoover St, Los Angeles, CA 90004",
    ownerName: "Harold J. Hanable",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Since 1927! A+ BBB. Top 5% BuildZoom. NO website.",
    dateAdded: "2026-03-24",
    tags: ["VIP", "Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 17,
    businessName: "US Plumbing",
    category: "Plumbing",
    phone: "(626) 354-1066",
    address: "Los Angeles, CA 90035",
    ownerName: "Alan",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Owner Alan. Pico-Robertson. Yelp only.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 18,
    businessName: "JLB Plumbing",
    category: "Plumbing",
    phone: "(323) 425-5780",
    address: "117 E 99th St, Los Angeles, CA 90003",
    ownerName: "Juan / Jose",
    email: "",
    websiteUrl: "https://jlbplumbing.org",
    websiteStatus: "Basic",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "29+ yrs. License #1011200. Basic site.",
    dateAdded: "2026-03-24",
    tags: ["Needs Social"],
    activities: [],
  },
  {
    id: 19,
    businessName: "Jose Express Plumbing",
    category: "Plumbing",
    phone: "(213) 864-9445",
    address: "Los Angeles, CA 90006",
    ownerName: "Jose",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "Low",
    leadStatus: "Not Contacted",
    notes: "Since 1991. Has Facebook but NO website.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website"],
    activities: [],
  },
  {
    id: 20,
    businessName: "Real Plumbers Inc.",
    category: "Plumbing",
    phone: "(323) 821-7922",
    address: "11300 Exposition Blvd, Los Angeles, CA 90064",
    ownerName: "Jose Luis Cabrales",
    email: "josecbrls@yahoo.com",
    websiteUrl: "https://realplumbersinc.com",
    websiteStatus: "Basic",
    socialStatus: "Low",
    leadStatus: "Not Contacted",
    notes: "164 Yelp reviews, 4.7 stars.",
    dateAdded: "2026-03-24",
    tags: [],
    activities: [],
  },
  {
    id: 21,
    businessName: "LB Plumbing",
    category: "Plumbing",
    phone: "(818) 415-2290",
    address: "6300 Laurel Canyon Blvd, NoHo, CA 91606",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Latinx-owned. SFV. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 22,
    businessName: "Incredible Plumber",
    category: "Plumbing",
    phone: "(818) 300-2955",
    address: "Reseda, CA",
    ownerName: "Christian",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Praised for honesty. NO website. SFV.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 23,
    businessName: "Silvas Plumbing",
    category: "Plumbing",
    phone: "",
    address: "Sylmar, CA 91342",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "32 Yelp reviews. Sylmar. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 24,
    businessName: "Daryl's Plumbing",
    category: "Plumbing",
    phone: "",
    address: "Lancaster, CA 93535",
    ownerName: "Daryl",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Lancaster. 27 Yelp reviews. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 25,
    businessName: "Salas Plumbing & Rooter",
    category: "Plumbing",
    phone: "(818) 734-7333",
    address: "Van Nuys, CA 91406",
    ownerName: "Francisco Salas",
    email: "",
    websiteUrl: "https://salasplumbingnrooter.com",
    websiteStatus: "Outdated",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Family-owned SFV 20 yrs. Outdated website.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website"],
    activities: [],
  },
  {
    id: 26,
    businessName: "Affordable Roofing",
    category: "Roofing",
    phone: "(323) 800-2022",
    address: "3540 Wilshire Blvd, Los Angeles, CA 90010",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "Outdated",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Est. 2015. Wix placeholder. Foremen 20+ yrs.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website"],
    activities: [],
  },
  {
    id: 27,
    businessName: "Delcid Roofing",
    category: "Roofing",
    phone: "(818) 612-9736",
    address: "Mission Hills, CA 91345",
    ownerName: "Jose Roberto Delcid",
    email: "",
    websiteUrl: "https://delcid-roofing.com",
    websiteStatus: "Basic",
    socialStatus: "Low",
    leadStatus: "Not Contacted",
    notes: "Est. 1997. Top 5% BuildZoom.",
    dateAdded: "2026-03-24",
    tags: [],
    activities: [],
  },
  {
    id: 28,
    businessName: "One Stop Roofing",
    category: "Roofing",
    phone: "(877) 868-7663",
    address: "Woodland Hills, CA 91367",
    ownerName: "David",
    email: "david@1stoproofing.com",
    websiteUrl: "https://1stoproofing.com",
    websiteStatus: "Basic",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Est. 2008. Contact David.",
    dateAdded: "2026-03-24",
    tags: ["Needs Social"],
    activities: [],
  },
  {
    id: 29,
    businessName: "Cabrera Roofing",
    category: "Roofing",
    phone: "(818) 397-5297",
    address: "Sun Valley, CA 91352",
    ownerName: "Alan Cabrera",
    email: "",
    websiteUrl: "https://cabreraroofingconstructioninc.com",
    websiteStatus: "Basic",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Family-owned since 2006. Top 3% BuildZoom.",
    dateAdded: "2026-03-24",
    tags: ["Needs Social"],
    activities: [],
  },
  {
    id: 30,
    businessName: "L.A. Roofing",
    category: "Roofing",
    phone: "(855) 711-7222",
    address: "Encino, CA 91316",
    ownerName: "",
    email: "",
    websiteUrl: "https://laroofingandbuilders.com",
    websiteStatus: "Basic",
    socialStatus: "Low",
    leadStatus: "Not Contacted",
    notes: "Owens Corning Preferred. 62 Yelp reviews.",
    dateAdded: "2026-03-24",
    tags: [],
    activities: [],
  },
  {
    id: 31,
    businessName: "NR Roofing",
    category: "Roofing",
    phone: "(818) 433-8632",
    address: "San Fernando Valley, CA",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Since 2012. NO website. SFV.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 32,
    businessName: "Premier Roofing",
    category: "Roofing",
    phone: "(818) 572-7240",
    address: "San Fernando, CA 91344",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Yelp only — NO website.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 33,
    businessName: "Dilligent Roofing",
    category: "Roofing",
    phone: "",
    address: "San Fernando Valley, CA",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Newer company. 48 Yelp photos.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 34,
    businessName: "AV Roofing & Construction",
    category: "Roofing",
    phone: "",
    address: "Lancaster, CA",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "Low",
    leadStatus: "Not Contacted",
    notes: "Lancaster. Facebook but NO website.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website"],
    activities: [],
  },
  {
    id: 35,
    businessName: "Great Valley Roofing",
    category: "Roofing",
    phone: "",
    address: "Antelope Valley, CA",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "AV area. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 36,
    businessName: "Victoria's Housekeeping",
    category: "Cleaning Services",
    phone: "(818) 745-4249",
    address: "San Fernando Valley, CA",
    ownerName: "Victoria",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "SFV. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 37,
    businessName: "Juanita's House Cleaning",
    category: "Cleaning Services",
    phone: "(818) 825-3662",
    address: "Northridge, CA",
    ownerName: "Juanita",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Northridge / SFV. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 38,
    businessName: "Adriana Zapata's Cleaning",
    category: "Cleaning Services",
    phone: "",
    address: "Palmdale, CA",
    ownerName: "Adriana Zapata",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Palmdale. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 39,
    businessName: "Candida's Housekeeping",
    category: "Cleaning Services",
    phone: "",
    address: "Santa Clarita, CA",
    ownerName: "Candida",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "14 years! Santa Clarita. NO website.",
    dateAdded: "2026-03-24",
    tags: ["VIP", "Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 40,
    businessName: "Rosita's Cleaning",
    category: "Cleaning Services",
    phone: "",
    address: "San Fernando Valley, CA",
    ownerName: "Rosita",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "SFV. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 41,
    businessName: "Two Sisters Cleaning",
    category: "Cleaning Services",
    phone: "",
    address: "San Fernando Valley, CA",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "SFV. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 42,
    businessName: "CARS Cristian's Auto Repair",
    category: "Auto Repair / Mechanics",
    phone: "(661) 726-9715",
    address: "Lancaster, CA",
    ownerName: "Cristian",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Lancaster. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 43,
    businessName: "Y&Y Automotive",
    category: "Auto Repair / Mechanics",
    phone: "(661) 942-5500",
    address: "Lancaster, CA",
    ownerName: "Yuri Gonzalez",
    email: "",
    websiteUrl: "",
    websiteStatus: "Outdated",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Outdated site. Upgrade candidate.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website"],
    activities: [],
  },
  {
    id: 44,
    businessName: "Quality Automotive",
    category: "Auto Repair / Mechanics",
    phone: "",
    address: "Palmdale, CA",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Family-owned. Palmdale. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 45,
    businessName: "Alberto's Transmissions",
    category: "Auto Repair / Mechanics",
    phone: "(661) 202-9760",
    address: "Lancaster, CA",
    ownerName: "Alberto",
    email: "",
    websiteUrl: "",
    websiteStatus: "Outdated",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Since 1995. 30 yrs. Basic site.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website"],
    activities: [],
  },
  {
    id: 46,
    businessName: "Advanced Level Automotive",
    category: "Auto Repair / Mechanics",
    phone: "(661) 225-9435",
    address: "Palmdale, CA",
    ownerName: "Jose",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Palmdale. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 47,
    businessName: "Corky's Auto Repair",
    category: "Auto Repair / Mechanics",
    phone: "(661) 943-4583",
    address: "Lancaster, CA",
    ownerName: "Corky",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Since 1972! 50+ years. NO website.",
    dateAdded: "2026-03-24",
    tags: ["VIP", "Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 48,
    businessName: "Jorge's HVAC",
    category: "HVAC / Electrical",
    phone: "(818) 857-6345",
    address: "San Fernando Valley, CA",
    ownerName: "Jorge",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Veteran-owned. New (2024). SFV. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 49,
    businessName: "George's Electric",
    category: "HVAC / Electrical",
    phone: "(818) 356-1200",
    address: "Sylmar, CA",
    ownerName: "George",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Sylmar electrician. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 50,
    businessName: "Integrity Heating & Air",
    category: "HVAC / Electrical",
    phone: "(661) 916-5715",
    address: "Palmdale, CA",
    ownerName: "Jimmy Nuttall",
    email: "",
    websiteUrl: "",
    websiteStatus: "Outdated",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Palmdale. Outdated site.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website"],
    activities: [],
  },
  {
    id: 51,
    businessName: "All For One Electric",
    category: "HVAC / Electrical",
    phone: "(661) 409-4477",
    address: "Palmdale, CA",
    ownerName: "Arturo Robles",
    email: "",
    websiteUrl: "",
    websiteStatus: "Basic",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Palmdale. Basic site.",
    dateAdded: "2026-03-24",
    tags: ["Needs Social"],
    activities: [],
  },
  {
    id: 52,
    businessName: "Mike Miller HVAC",
    category: "HVAC / Electrical",
    phone: "(661) 621-1056",
    address: "Santa Clarita, CA",
    ownerName: "Mike Miller",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "233 Yelp reviews! NO website. VERY HIGH PRIORITY.",
    dateAdded: "2026-03-24",
    tags: ["VIP", "Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 53,
    businessName: "Angel Electric",
    category: "HVAC / Electrical",
    phone: "(818) 570-0552",
    address: "Sylmar, CA",
    ownerName: "Angel",
    email: "",
    websiteUrl: "",
    websiteStatus: "Basic",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Sylmar. Basic site.",
    dateAdded: "2026-03-24",
    tags: ["Needs Social"],
    activities: [],
  },
  {
    id: 54,
    businessName: "Robs Handy Man Service",
    category: "General Contractor",
    phone: "(818) 384-0458",
    address: "San Fernando Valley, CA",
    ownerName: "Rob",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "SFV handyman. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 55,
    businessName: "HappyHandyman",
    category: "General Contractor",
    phone: "(323) 602-3790",
    address: "Palmdale, CA",
    ownerName: "Rommel R.",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "32 Yelp reviews. Palmdale. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 56,
    businessName: "Rafael G Handyman",
    category: "General Contractor",
    phone: "(213) 925-6783",
    address: "Palmdale, CA",
    ownerName: "Rafael G.",
    email: "",
    websiteUrl: "",
    websiteStatus: "Outdated",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Since 1995. 30 yrs. Basic site.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website"],
    activities: [],
  },
  {
    id: 57,
    businessName: "R & Y Handyman",
    category: "General Contractor",
    phone: "",
    address: "Pacoima, CA",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "Basic",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Pacoima. Basic site.",
    dateAdded: "2026-03-24",
    tags: ["Needs Social"],
    activities: [],
  },
  {
    id: 58,
    businessName: "Nuance Electric & Handyman",
    category: "General Contractor",
    phone: "",
    address: "Sylmar, CA",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "Sylmar. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 59,
    businessName: "Taqueria Los Compadres",
    category: "Restaurant / Food",
    phone: "(818) 834-6990",
    address: "Sylmar, CA",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "150 Yelp reviews! Popular Sylmar taqueria. NO website.",
    dateAdded: "2026-03-24",
    tags: ["VIP", "Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 60,
    businessName: "El Caporal",
    category: "Restaurant / Food",
    phone: "(818) 768-3025",
    address: "Sun Valley, CA",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "78 Yelp reviews. Sun Valley. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 61,
    businessName: "Tacos El Canelo No. 2",
    category: "Restaurant / Food",
    phone: "(818) 834-1627",
    address: "Pacoima, CA",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "24 YEARS! 120 Yelp reviews. NO website.",
    dateAdded: "2026-03-24",
    tags: ["VIP", "Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 62,
    businessName: "Taqueria La Famosa",
    category: "Restaurant / Food",
    phone: "(661) 285-5636",
    address: "Palmdale, CA",
    ownerName: "",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "94 Yelp reviews. Palmdale. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 63,
    businessName: "La Jefa Food Truck",
    category: "Restaurant / Food",
    phone: "(661) 480-4852",
    address: "Lancaster, CA",
    ownerName: "Guadalupe L.",
    email: "",
    websiteUrl: "",
    websiteStatus: "None",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "15+ years catering. Lancaster. NO website.",
    dateAdded: "2026-03-24",
    tags: ["Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
  {
    id: 64,
    businessName: "Tacos El Afro",
    category: "Restaurant / Food",
    phone: "(661) 733-7273",
    address: "Palmdale, CA",
    ownerName: "Afrodicio M.",
    email: "",
    websiteUrl: "",
    websiteStatus: "Outdated",
    socialStatus: "None",
    leadStatus: "Not Contacted",
    notes: "173 Yelp reviews! Award-winning. Square page only.",
    dateAdded: "2026-03-24",
    tags: ["VIP", "Hot Lead", "Needs Website", "Needs Social"],
    activities: [],
  },
];

export const calculateLeadScore = (lead: any) => {
  let score = 0;
  if (lead.websiteStatus === "None") score += 3;
  if (lead.websiteStatus === "Outdated") score += 1;
  if (lead.socialStatus === "None") score += 2;
  if (lead.tags?.includes("VIP")) score += 2;
  if (lead.tags?.includes("Hot Lead")) score += 1;
  return Math.min(score, 10);
};

export const getLeadScoreColor = (score: number) => {
  if (score >= 7) return "text-red-400 bg-red-500/15 border-red-500/20";
  if (score >= 4) return "text-amber-400 bg-amber-500/15 border-amber-500/20";
  return "text-emerald-400 bg-emerald-500/15 border-emerald-500/20";
};

export const formatTimeAgo = (dateString?: string) => {
  if (!dateString) return "";
  const days = Math.floor(
    (Date.now() - new Date(dateString).getTime()) / 86400000,
  );
  if (days === 0) return "Today";
  if (days === 1) return "Yesterday";
  if (days < 7) return days + "d ago";
  if (days < 30) return Math.floor(days / 7) + "w ago";
  return Math.floor(days / 30) + "mo ago";
};
